#!/usr/bin/perl
use strict;
use warnings; 

use Getopt::Std;
my %opt;
getopts( 'vrh', \%opt);

my $run=<<RUN;
TEST_AUTHOR=1 HARNESS_PERL_SWITCHES=-MDevel::Cover make test
cover
cover -report text > cover_report.txt
RUN

unless( @ARGV) 
  { system "cover -delete; $run"; exit; }

if( @ARGV)
  { foreach my $test (@ARGV)
      { system "TEST_AUTHOR=1 $^X -MDevel::Cover $test"; }
  }
else
  {  system "TEST_AUTHOR=1 HARNESS_PERL_SWITCHES=-MDevel::Cover make test"; }

system "cover && cover -report text > cover_report.txt";

__END__
=head1 NAME

  cover_twig -- generates test coverage for XML::Twig

=head1 OPTIONS

  -r reset (delete) the coverage DB

=head1 EXAMPLES

  ./cover_twig 
  ./cover_twig -r
  ./cover_twig t/test_3_36.t

