---
abstract: 'XML, The Perl Way'
author:
  - 'Michel Rodriguez <mirod@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921, CPAN::Meta::Converter version 2.120630, CPAN::Meta::Converter version 2.133380, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Twig
no_index:
  directory:
    - t
    - inc
recommends:
  Encode: 2.42_01
  Scalar::Util: 1.23
  XML::XPathEngine: 0.13
requires:
  XML::Parser: 2.23
resources:
  repository: http://github.com/mirod/xmltwig
version: 3.41
